apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          securityContext:
            runAsUser: 0 # run jenkins logged in as root
          # command: ['/bin/sh', '-c']
          # args: ['apt-get update']
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: docker-vol
              mountPath: /var/run/docker.sock
            - name: jenkins-vol
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-vol
          emptyDir: {}
        - name: docker-vol
          hostPath:
            path: /var/run/docker.sock
